version: '3.8'

services:
  crud-app:
    depends_on:
      - database
    build: 
      context: ./crm-data-jpa-thymeleaf-crud
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped

  database:
    build: 
      context: mysql
    command: ./mysql/mysql-entrypoint.sh
    ports:
      - 3306:3306
    restart: unless-stopped