version: '3.8'

services:

  database:
    image: mysql:8
    container_name: users-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"

  crud-app:
    build: 
      context: ./crm-data-jpa-thymeleaf-crud
      dockerfile: Dockerfile.jar-ready
    container_name: crud-app
    depends_on:
      - database
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_PASSWORD
      - SERVER_PORT=$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ./.env
  
  server:
    container_name: nginx-server
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - crud-app