version: '3.8'

services:

  database:
    image: mysql:8
    container_name: users-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

    volumes:
      - "./init:/docker-entrypoint-initdb.d"

  # adminer:
  #   image: adminer
  #   restart: always
  #   container_name: mysql-adminer
  #   ports:
  #     - $ADMINER_LOCAL_PORT:$ADMINER_DOCKER_PORT

  crud-app:
    build: 
      context: ./crm-data-jpa-thymeleaf-crud
      dockerfile: Dockerfile.jar-ready
    container_name: crud-app
    depends_on:
      database:
        condition: "service_started"
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_PASSWORD
      - SERVER_PORT=$SPRING_DOCKER_PORT
    # environment:
    #   APP_PROPERTIES_JSON: '{
    #     "spring.datasource.url":"jdbc:mysql://database:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC",
    #     "spring.datasource.username":"$MYSQLDB_USER",
    #     "spring.datasource.password":"$MYSQLDB_PASSWORD",
    #     "server.port":"$SPRING_DOCKER_PORT" }'
    volumes:
      - .m2:/root/.m2
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ./.env